exec-once = /usr/bin/hyprland-per-window-layout
# Hyprland configuration overrides
# Add your custom settings here

# Example overrides:
# $mainMod = SUPER
# $terminal = uwsm app -- alacritty
# $browser = chromium --force-device-scale-factor=0.8

# Use single default monitor (see all monitors with: hyprctl monitors)
# monitor=,preferred,auto,1.6

# trigger when the switch is turning on
# bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
# trigger when the switch is turning off
# bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, preferred, auto, 1.6"

# bind = SUPER SHIFT, D, exec, hyprctl keyword monitor eDP-1, disable
# bind = SUPER SHIFT, F, exec, hyprctl keyword monitor eDP-1, preferred, auto, 1.6

# unbind = SUPER, D
# bindd = SUPER, D, Discord, exec, omarchy-launch-webapp "https://discord.com/channels/@me"
# unbind = SUPER, G
# bindd = SUPER, G, Notion, exec, omarchy-launch-webapp "https://www.notion.so/"

# unbind = SUPER, return
# bindd = SUPER, return, Terminal, exec, $terminal
# unbind = SUPER, B
# bindd = SUPER, B, Browser, exec, $browser

unbind = SUPER, h
unbind = SUPER, j
unbind = SUPER, J
unbind = SUPER, k
unbind = SUPER, K
unbind = SUPER, l
unbind = SUPER, M

# Move focus with mainMod + arrow keys
bind = SUPER, h, movefocus, l
bind = SUPER, j, movefocus, d
bind = SUPER, k, movefocus, u
bind = SUPER, l, movefocus, r

bindd = SUPER, M, Toggle workspace layout, exec, omarchy-hyprland-workspace-layout-toggle
# Workspace stuff
unbind = SUPER, I
unbind = SUPER, U
bindd = SUPER, I, Next workspace, workspace, e+1
bindd = SUPER, U, Previous workspace, workspace, e-1

# Telegram keybinding
unbind = SUPER SHIFT, T
bindd = SUPER SHIFT, T, Activity, exec, Telegram

misc {
    mouse_move_enables_dpms=true
    key_press_enables_dpms=true
    focus_on_activate = false
}
input {
  # Use multiple keyboard layouts and switch between them with Alt + Space
  kb_layout = us,ru
  kb_options = caps:hyper, grp:alt_shift_toggle, ctrl:nocaps


  # Change speed of keyboard repeat
  repeat_rate = 50
  repeat_delay = 220

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35

  # touchpad {
  #   # Use natural (inverse) scrolling
  #   # natural_scroll = true
  #
  #   # Use two-finger clicks for right-click instead of lower-right corner
  #   # clickfinger_behavior = true
  #
  #   # Control the speed of your scrolling
  #   scroll_factor = 0.4
  # }
}

general {
    # No gaps between windows or borders
    gaps_in = 2
    gaps_out = 3
    border_size = 2

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8

    active_opacity = 1.1
    inactive_opacity = 1.1
    fullscreen_opacity = 1.1

    blur {
        enabled = true
        size = 1
        passes = 2
        ignore_opacity = true
        xray = true
        new_optimizations = true
        # brightness = 1.0
        # popups = false
    }

    # shadow {
    #     enabled = true
    # }
}

animations {
  enabled = true
}

# Windowrules
## Browser
windowrule = match:class ^(chromium)$, workspace 9
windowrule = match:class ^(google-chrome)$, workspace 9
## Telegram
windowrule = match:class ^(org.telegram.desktop)$|^(TelegramDesktop)$, workspace 7
